In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from model import SimulacionModel

In [3]:
params = {'steps': 10, 'compradores':10, 'mercados':5}

In [4]:
model = SimulacionModel(params)

result = model.run()

Completed: 10 steps
Run time: 0:00:00.004949
Simulation finished

In [5]:
result.variables.SimulacionModel

,comprador_no_compra,mercado_gini,mercado_money,comprador_money,ventas,price_Manzanas,items_Manzanas,price_Peras,items_Peras
t,,,,,,,,,
0,10,0.000000,None,None,None,None,None,None,None
1,0,0.015385,None,None,None,None,None,None,None
2,0,0.029630,None,None,None,None,None,None,None
3,0,0.043806,None,None,None,None,None,None,None
4,0,0.056944,None,None,None,None,None,None,None
5,0,0.074124,None,None,None,None,None,None,None
6,0,0.090032,None,None,None,None,None,None,None
7,0,0.105393,None,None,None,None,None,None,None
8,0,0.123529,None,None,None,None,None,None,None
9,0,0.139691,None,None,None,None,None,None,None
10,0,0.140761,"[200, 145, 116, 100, 175]","[5, 5, 5, 5, 9, 9, 14, 5, 5, 2]","[44, 25, 12, 0, 36]","[5, 3, 2, 1, 4]","[1, 1, 0, 0, 1, 1, 1, 1, 0, 1]","[2, 1, 1, 1, 2]","[2, 2, 2, 2, 2, 2, 2, 2, 2, 2]"